//------------------------------------------------------------------------------
//  BudgetClass.cs
//
//  Implementation of: BudgetClass (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:07
//  Original author: Miguel
//------------------------------------------------------------------------------

using Domion.Lib.Display;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace DFlow.Budget.Core.Model
{
    public class BudgetClass
    {
        public BudgetClass()
        {
            BudgetItems = new HashSet<BudgetItem>();
            TransactionType = TransactionType.Income;
        }

        public virtual decimal BaseTotal { get; set; }

        public virtual ICollection<BudgetItem> BudgetItems { get; set; }

        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public virtual string Name { get; set; } // Key data ----------

        public virtual Byte[] RowVersion { get; set; }

        public virtual int SortOrder { get; set; }

        public virtual Tenant Tenant { get; set; }

        public virtual int Tenant_Id { get; set; }

        public virtual TransactionType TransactionType { get; set; }

        public void Calculate()
        {
            BaseTotal = BudgetItems.Sum(bi => bi.BaseAmount);

            foreach (BudgetItem item in BudgetItems)
            {
                item.Percent = Percent.Value(item.BaseAmount, BaseTotal);
            }
        }
    }
}
