//------------------------------------------------------------------------------
//  BudgetClass.cs
//
//  Implementation of: BudgetClass (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 02-jun-2017 10:49:07
//  Original author: Miguel
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DFlow.Budget.Core.Model
{
	public class BudgetClass
	{
		public BudgetClass()
		{
			BudgetLines = new HashSet<BudgetLine>();
			TransactionType = TransactionType.Income;
		}

		public virtual ICollection<BudgetLine> BudgetLines { get; set; }

		public int Id { get; set; }

		[Required]
		[MaxLength(100)]
		public virtual string Name { get; set; } // Key data ----------

		public virtual Byte[] RowVersion { get; set; }

		public virtual int SortOrder { get; set; }

		public virtual Tenant Tenant { get; set; }

		public virtual int Tenant_Id { get; set; }

		public virtual TransactionType TransactionType { get; set; }
	}
}
