//------------------------------------------------------------------------------
//  BudgetLine.cs
//
//  Implementation of: BudgetLine (Class) <<ef-entity>>
//  Generated by Domion-MDA - http://www.coderepo.blog/domion
//
//  Created on     : 06-ago-2017 19:40:50
//  Original author: Miguel
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace DFlow.Budget.Core.Model
{
    public class BudgetItem
    {
        public virtual decimal BaseAmount { get; set; }

        public virtual BudgetClass BudgetClass { get; set; }

        public virtual int BudgetClass_Id { get; set; }

        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public virtual string Name { get; set; }

        public virtual decimal Percent { get; set; }

        // Key data ----------

        public virtual Byte[] RowVersion { get; set; }

        public virtual int SortOrder { get; set; }
    }
}
